### ISSUE TITLE
How to setup docker for Windows?

### ISSUE THREAD

**Issue by sathishsoundharajan** [dwyl/learn-docker#12]
Can we have explicit tutorial for windows users?

Most of them are struggling to setup docker, coz this issue,

```
http://127.0.0.1:2375/v1.19/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.. Are you trying to connect to a TLS-enabled daemon without TLS?
```

There is a solution, but not in detail.

**Comment by nelsonic** [comment]
@bboysathish please feel free to PR. we don't use Windows and don't have time in the next few weeks to do a windows-focussed tutorial... :+1:

**Comment by sathishsoundharajan** [comment]
@nelsonic  i am also encountering that issue. After resolving that will make PR :+1: 

Will have this issue open till i make PR (purely for tracking purpose.)

**Comment by nelsonic** [comment]
Sweet! good luck! :8ball:

**Comment by sathishsoundharajan** [comment]
FWIW, I have opened a Bug about this in docker ToolBox 
https://github.com/docker/toolbox/issues/265

**Comment by nelsonic** [comment]
Nice one.

**Comment by sathishsoundharajan** [comment]
I am closing this as of now. Docker ToolBox team taking too much time to respond. No reason for this issue to open for that long. Will Open it and Make PR after resolving the Docker Issue.

**Comment by nelsonic** [comment]
Thanks @bboysathish we don't _mind_ keeping issues open as they inform others that there's a pending hurdle. but yeah, when you figure it out we'll be _delighted_ to see a PR! :+1:
