### ISSUE TITLE
Bug: update readme - intro video not working

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-docker#17]
Bug: update readme - intro video not working

> Watch the intro vide: https://www.youtube.com/watch?v=ZzQfxoMFH0U

![image](https://user-images.githubusercontent.com/16775804/54420484-04f23680-4702-11e9-9717-8b9c3b084554.png)

- [x] Remove broken link
- [x] check for more recent working intro video

**Comment by Cleop** [comment]
I am going to replace it with the video suggested in #14

**Comment by nelsonic** [comment]
@Cleop cool. 😎

**Comment by Cleop** [comment]
Closing as this has now been removed and merged 😊
