### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-docker#20]
@Cleop did you install the Docker Mac app on your computer?
Were the installation instructions [https://github.com/dwyl/learn-docker#installation](https://github.com/dwyl/learn-docker/tree/31fd4a78280870080f61f85ed14035ba9ca0914f#installation) still relevant?

**Comment by Cleop** [comment]
The existing instructions are no longer up to date. From what I understand it is no longer necessary to download Docker Toolkit alongside Docker Desktop: https://docs.docker.com/docker-for-mac/docker-toolbox/. I believe Docker Desktop is sufficient on Mac providing you have Mac OS Sierra or later.

This article is a well written and up to date summary of how to download Docker for Mac: https://www.imore.com/how-run-docker-your-mac

I am integrating its points into our readme.

**Comment by nelsonic** [comment]
@cleop thanks for updating the instructions. 🤩
