### ISSUE TITLE
Demo is not available

### ISSUE THREAD

**Issue by omer727** [dwyl/learn-docker#5]
What happened to this demo? it's not working.

When going to this link: https://www.docker.com/tryit/

**Comment by nelsonic** [comment]
Well that's annoying ... it used to be an online tutorial ... now they are forcing people to install and run it locally...

**Comment by nelsonic** [comment]
@omer727 if you find a suitable alternative, please let us know!

**Comment by sathishsoundharajan** [comment]
@nelsonic  How about this self-paced learning link.

https://training.docker.com/self-paced-training

**Comment by nelsonic** [comment]
That appears to be a good _alternative_. but the old `/tryit` link did not require any installation.
Feel free to substitute the link in a PR. :+1:

**Comment by Cleop** [comment]
- [x] remove the demo that doesn't work. 

I won't be adding in the suggested link above as it appears that link is now out of date and redirects to a paid, in-person course schedule which I don't think is the right fit for this remote, free tutorial.

**Comment by nelsonic** [comment]
@omer727 please re-open if you feel this is still an issue. 
thanks again for reporting it! 👍
