### ISSUE TITLE
Update!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-docker#6]
Docker has changed a _lot_ in the last year, this tutorial needs updating... :hourglass:

**Comment by nelsonic** [comment]
- https://www.docker.com/toolbox
- https://kitematic.com/docs/

**Comment by nelsonic** [comment]
http://code.tutsplus.com/tutorials/easily-deploy-redis-backed-web-apps-with-docker--cms-20405

**Comment by Cleop** [comment]
I'm also adding into this update a bit more detail to the what/why sections of the readme.

**Comment by nelsonic** [comment]
@cleop thanks for updating. ☀️
